# Description
#
#
#
devices:
- name: PCM_Spiral_te1550nm
  wavelength: 1550
  polarization: TE
  target_prefix: "PCM_SpiralWG"
  target_suffix: "TE"
  characterization: "cutback_waveguide"
  port: 1

- name: PCM_Straight_te1550nm
  wavelength: 1550
  polarization: TE
  target_prefix: "PCM_StraightWGloss"
  target_suffix: "TE"
  characterization: "cutback_waveguide"
  port: 1

-  name: PCM_YBranch_te1550nm
   wavelength: 1550
   polarization: TE
   target_prefix: "PCM_Ycutbacks_N"
   target_suffix: "_2"
   characterization: "cutback_device"
   port: 1
