# Note:
# yaml file should be stored in folder with device name folders
#
#

devices:
- name: PCM_Straight
  wavelength: 1550
  characterization: "Insertion Loss (dB/cm)"
  polarization: TE
  target_prefix: "PCM_StraightWGloss"
  target_suffix: "TE"
  wavelength_min:
  wavelength_max:
  type:
  port: 1

- name: PCM_Spiral
  wavelength: 1550
  characterization: "Insertion Loss (dB/cm)"
  polarization: TE
  target_prefix: "PCM_SpiralWG"
  target_suffix: "TE"
  wavelength_min:
  wavelength_max:
  type:
  port: 1

- name: PCM_SWG
  wavelength: 1550
  characterization: "Insertion Loss (dB/cm)"
  polarization: TE
  target_prefix: "PCM_SWGloss"
  target_suffix: "TE"
  wavelength_min:
  wavelength_max:
  type:
  port: 1

- name: PCM_YBranch
  characterization: "Insertion Loss (dB/device)"
  wavelength: 1550
  polarization: TE
  target_prefix: "PCM_Ycutbacks_N"
  target_suffix: "_2"
  wavelength_min:
  wavelength_max:
  type:
  port: 1

- name: PCM_ContraDC
  wavelength: 1550
  characterization: "Insertion Loss (dB/device)"
  polarization: TE
  target_prefix: "PCMcontraDCcascaded"
  target_suffix: ""
  wavelength_min: 1548
  wavelength_max: 1556
  type: 'CDC'
  port: 2

- name: PCM_Bragg_reg
  characterization: "Bragg Drift (nm)"
  wavelength: 1550
  polarization: TE
  device_prefix: "PCM_Bragg_C__1000N"
  device_suffix: "nmPeriod500nmW20nmdW0Apo"
  type:
  sim_label: "Simulation (1550_SiO2 Clad)"
  tolerance:
  N_seg:
  threshold_val: 0.4
  port_drop: 1 # port in the measurement set containing the drop port data
  port_thru: 1 # port in the measurement set containing the through port data

- name: PCM_Bragg_sweep
  wavelength: 1550
  characterization: "Bragg Drift (nm)"
  polarization: TE
  device_prefix: "PCM_BraggSweepDW500N318nmPeriod500nmW"
  device_suffix: "nmdW0Apo"
  type: "sweep"
  sim_label:
  tolerance:
  N_seg:
  threshold_val: 0.12
  port_drop: 1 # port in the measurement set containing the drop port data
  port_thru: 1 # port in the measurement set containing the through port data

- name: PCM_GIndex
  wavelength: 1550
  characterization: "Group Index"
  polarization: TE
  device_prefix: "PCM_DC_Length"
  device_suffix: "um_2"
  measurement_label: "1550" # adjusts set of simulation data used for analysis
  peak_prominence: 0.7
  port_cross: 1 # port containing the cross-port data to process
  port_bar: 0 # port containing the bar-port data to process
