# Note:
# yaml file should be stored in folder with xxxx_TE folders
#
#

devices:
- name: PCM_Straight
  wavelength: 1310
  characterization: "Insertion Loss (dB/cm)"
  polarization: TM
  target_prefix: "PCM_StraightLongWGloss"
  target_suffix: "TM"
  wavelength_min:
  wavelength_max:
  type:
  port: 1

- name: PCM_Spiral
  wavelength: 1310
  characterization: "Insertion Loss (dB/cm)"
  polarization: TM
  target_prefix: "PCM_SpiralWG"
  target_suffix: "TM"
  wavelength_min:
  wavelength_max:
  type:
  port: 1